version: '1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: holdyasql

  dash_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    environment:
      - DATABASE=postgres
      - USER=postgres
      - PASSWORD=holdyasql
      - HOST=localhost
      - PORT=5432
    depends_on:
      - postgres

